const QuestionDataBase = [
  { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Central Processor Unit"], correct: "Central Processing Unit" },
  { question: "Which device is used as the primary input device for a computer?", options: ["Monitor", "Keyboard", "Printer", "Speaker"], correct: "Keyboard" },
  { question: "What is the main function of an operating system?", options: ["Word Processing", "Managing Hardware & Software", "Browsing the Internet", "Playing Games"], correct: "Managing Hardware & Software" },
  { question: "Which of the following is an example of an output device?", options: ["Mouse", "Keyboard", "Monitor", "Microphone"], correct: "Monitor" },
  { question: "Which memory is volatile and loses data when power is turned off?", options: ["Hard Drive", "RAM", "ROM", "Flash Drive"], correct: "RAM" },
  { question: "What is the full form of HTTP?", options: ["HyperText Transfer Protocol", "HyperText Transmission Process", "High Transfer Technology Process", "Hyperlink Transfer Protocol"], correct: "HyperText Transfer Protocol" },
  { question: "Which of these is not an operating system?", options: ["Windows", "Linux", "Google Chrome", "MacOS"], correct: "Google Chrome" },
  { question: "What is the brain of the computer?", options: ["RAM", "CPU", "Hard Drive", "Motherboard"], correct: "CPU" },
  { question: "Which company developed the Windows operating system?", options: ["Apple", "Microsoft", "Google", "IBM"], correct: "Microsoft" },
  { question: "What does URL stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Unified Resource Link", "Uniform Retrieval Link"], correct: "Uniform Resource Locator" },
  { question: "Which storage device has the largest capacity?", options: ["USB Flash Drive", "Hard Drive", "CD-ROM", "Blu-ray Disc"], correct: "Hard Drive" },
  { question: "What is the name of the first computer programmer?", options: ["Ada Lovelace", "Charles Babbage", "Alan Turing", "John von Neumann"], correct: "Ada Lovelace" },
  { question: "What is the smallest unit of data in a computer?", options: ["Byte", "Bit", "Kilobyte", "Megabyte"], correct: "Bit" },
  { question: "Which generation of computers used integrated circuits?", options: ["First", "Second", "Third", "Fourth"], correct: "Third" },
  { question: "What is the process of starting a computer called?", options: ["Booting", "Loading", "Initiating", "Beginning"], correct: "Booting" },
  { question: "What is the default file extension for MS Word documents?", options: [".doc", ".txt", ".docx", ".pdf"], correct: ".docx" },
  { question: "Which shortcut key is used to save a document in MS Word?", options: ["Ctrl + P", "Ctrl + S", "Ctrl + N", "Ctrl + O"], correct: "Ctrl + S" },
  { question: "What is the default file extension for MS Excel?", options: [".xls", ".xlsx", ".csv", ".xlt"], correct: ".xlsx" },
  { question: "Which application is used for making presentations?", options: ["MS Word", "MS Excel", "MS PowerPoint", "MS Access"], correct: "MS PowerPoint" },
  { question: "Which function in MS Excel is used to find the sum of a range of numbers?", options: ["SUM()", "TOTAL()", "ADD()", "SUMMATION()"], correct: "SUM()" },
  { question: "Which feature in MS Word allows you to create letters and labels for multiple recipients?", options: ["Mail Merge", "Find and Replace", "Format Painter", "Table of Contents"], correct: "Mail Merge" },
  { question: "What is the shortcut key for printing a document?", options: ["Ctrl + P", "Ctrl + S", "Ctrl + N", "Ctrl + O"], correct: "Ctrl + P" },
  { question: "Which feature in MS Excel allows you to apply the same formatting to multiple cells?", options: ["Conditional Formatting", "Format Painter", "Data Validation", "Filter"], correct: "Format Painter" },
  { question: "Which function in MS Excel is used to find the average of a range of numbers?", options: ["AVG()", "AVERAGE()", "MEAN()", "MEDIAN()"], correct: "AVERAGE()" },
  { question: "What is the default file extension for LibreOffice Writer documents?", options: [".odt", ".doc", ".txt", ".pdf"], correct: ".odt" },
  { question: "Which LibreOffice application is used for creating spreadsheets?", options: ["Writer", "Calc", "Impress", "Base"], correct: "Calc" },
  { question: "Which feature in MS Word allows you to automatically generate a list of sources?", options: ["Citation", "Bibliography", "Footnote", "Endnote"], correct: "Bibliography" },
  { question: "What is the full form of IP in networking?", options: ["Internet Processing", "Internet Protocol", "Integrated Process", "Information Protocol"], correct: "Internet Protocol" },
  { question: "Which protocol is used for sending emails?", options: ["HTTP", "FTP", "SMTP", "SNMP"], correct: "SMTP" },
  { question: "Which one of these is a search engine?", options: ["Facebook", "Google", "WhatsApp", "Wikipedia"], correct: "Google" },
  { question: "What does HTML stand for?", options: ["Hyper Transfer Markup Language", "HyperText Markup Language", "High-Level Text Management Language", "None of the above"], correct: "HyperText Markup Language" },
  { question: "Which browser was the first to be developed?", options: ["Internet Explorer", "Chrome", "Netscape Navigator", "Mozilla Firefox"], correct: "Netscape Navigator" },
  { question: "Which of the following is used to protect a network from unauthorized access?", options: ["Firewall", "Antivirus", "Router", "Modem"], correct: "Firewall" },
  { question: "What is the main purpose of a domain name?", options: ["Identify a website", "Store data", "Provide internet speed", "Encrypt data"], correct: "Identify a website" },
  { question: "Which one of these is not a web browser?", options: ["Chrome", "Firefox", "Opera", "Windows"], correct: "Windows" },
  { question: "Which search engine is owned by Microsoft?", options: ["Google", "Yahoo", "Bing", "DuckDuckGo"], correct: "Bing" },
  { question: "Which service is used to transfer files over the internet?", options: ["HTTP", "FTP", "SMTP", "DNS"], correct: "FTP" },
  { question: "What does ISP stand for?", options: ["Internet Service Provider", "Internal Service Protocol", "Integrated Service Provider", "Internet Support Protocol"], correct: "Internet Service Provider" },
  { question: "Which of these is a method of securing a network?", options: ["Encryption", "Defragmentation", "Formatting", "Backup"], correct: "Encryption" },
  { question: "What does DNS stand for?", options: ["Domain Name System", "Digital Network Server", "Data Network Service", "Domain Network Service"], correct: "Domain Name System" },
  { question: "Which of these is a cloud storage service?", options: ["OneDrive", "FireFox", "GitHub", "Python"], correct: "OneDrive" },
  { question: "What is the term for a program that replicates itself to spread to other computers?", options: ["Virus", "Worm", "Trojan", "Spyware"], correct: "Worm" },
  { question: "Which planet is known as the Red Planet?", options: ["Mars", "Jupiter", "Saturn", "Venus"], correct: "Mars" },
  { question: "Who wrote the play 'Romeo and Juliet'?", options: ["William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"], correct: "William Shakespeare" },
  { question: "What is the capital city of Japan?", options: ["Tokyo", "Kyoto", "Osaka", "Nagoya"], correct: "Tokyo" },
  { question: "Which element has the chemical symbol 'O'?", options: ["Oxygen", "Gold", "Osmium", "Silver"], correct: "Oxygen" },
  { question: "In which year did the Titanic sink?", options: ["1912", "1905", "1920", "1935"], correct: "1912" },
  { question: "Who developed the theory of relativity?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], correct: "Albert Einstein" },
  { question: "Which type of memory is non-volatile and retains data even when the power is turned off?", options: ["RAM", "ROM", "Cache", "Register"], correct: "ROM" },
  { question: "Which memory type is the fastest and is located inside the CPU?", options: ["Hard Disk", "SSD", "Cache Memory", "Virtual Memory"], correct: "Cache Memory" },
  
]
export default QuestionDataBase;